### ISSUE TITLE
The sample demo in codesandbox get error

### ISSUE THREAD

**Issue by wiasliaw** [likecoin/likecoin#8]
1. https://codesandbox.io/s/likecoin-api-badge-demo-4mcc4

![image](https://user-images.githubusercontent.com/37038019/82721065-8a9d4900-9cec-11ea-8968-fde014e93b84.png)

2.  https://codesandbox.io/s/likecoin-oauth-demo-3u9qq

After clicking the button, the browser got below.

![image](https://user-images.githubusercontent.com/37038019/82721074-9be65580-9cec-11ea-902a-a1a4ef9e22e4.png)

**Comment by williamchong** [comment]
for 1, please browse the path `/badge/stat/liker.svg` as defined in express

for 2. please run the demo in new window instead of iframe, the error is due to.x-frame-option security setting

**Comment by wiasliaw** [comment]
TKS, I close this issue.

**Comment by williamchong** [comment]
maybe we can keep this issue open to improve unclear instructions

**Comment by williamchong** [comment]
updated with https://github.com/likecoin/likecoin/commit/82942db693b3a93818ee3185fe60a866a920d9f0 and https://github.com/likecoin/likecoin/commit/639db9d8a6592c96f8d7eb4263686ebac8dfc7dd to solve the issue
